// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnackAndTrack.DatabaseAccess;

namespace DatabaseAccess.Migrations
{
    [DbContext(typeof(SnackAndTrackDbContext))]
    partial class SnackAndTrackDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.FoodItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.FoodItemNutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NutrientId")
                        .HasColumnType("uuid");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("NutrientId");

                    b.ToTable("FoodItemNutrients");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.Nutrient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Nutrients");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.ServingSize", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FoodItemId")
                        .HasColumnType("uuid");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("UnitId");

                    b.ToTable("ServingSizes");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("UnitName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.UnitConversion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromUnitId")
                        .HasColumnType("uuid");

                    b.Property<double>("Ratio")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("ToUnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FromUnitId");

                    b.HasIndex("ToUnitId");

                    b.ToTable("UnitConversions");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.FoodItemNutrient", b =>
                {
                    b.HasOne("SnackAndTrack.DatabaseAccess.Entities.FoodItem", "FoodItem")
                        .WithMany("FoodItemNutrients")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackAndTrack.DatabaseAccess.Entities.Nutrient", "Nutrient")
                        .WithMany("FoodItemNutrients")
                        .HasForeignKey("NutrientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Nutrient");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.ServingSize", b =>
                {
                    b.HasOne("SnackAndTrack.DatabaseAccess.Entities.FoodItem", "FoodItem")
                        .WithMany("ServingSizes")
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SnackAndTrack.DatabaseAccess.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("UnitId");

                    b.Navigation("FoodItem");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.UnitConversion", b =>
                {
                    b.HasOne("SnackAndTrack.DatabaseAccess.Entities.Unit", "FromUnit")
                        .WithMany()
                        .HasForeignKey("FromUnitId");

                    b.HasOne("SnackAndTrack.DatabaseAccess.Entities.Unit", "ToUnit")
                        .WithMany()
                        .HasForeignKey("ToUnitId");

                    b.Navigation("FromUnit");

                    b.Navigation("ToUnit");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.FoodItem", b =>
                {
                    b.Navigation("FoodItemNutrients");

                    b.Navigation("ServingSizes");
                });

            modelBuilder.Entity("SnackAndTrack.DatabaseAccess.Entities.Nutrient", b =>
                {
                    b.Navigation("FoodItemNutrients");
                });
#pragma warning restore 612, 618
        }
    }
}
